const state={
	application:{
		isShowIntro:true,//是否显示介绍屏
		isShowSplash:false,//是否显示闪屏
		tabSelect:'aichoose',//底部栏选中
	},
	aichoose:{
		hasLastResult:true,//是否存在上一次选装结果
		fetchState:'start/error/success',//请求选装结果状态
		//上一次选装结果
		lastResult:{
			time:86400,//上次选装时间
			id:1024,//选装结果id
			match_tag:"EAAEAC",//匹配的标签
			similar_tag:["EAAEEC","EAAEEC"],//模糊匹配标签
			equip_word:[
				'中级',
				'缓震型',
				'中底:缓震型中底，弹性十足，中级缓冲，保护膝盖',
				'外底:耐磨橡胶，纹路细腻，抓地力强'
			],//形容鞋子的话术
			person_slogan:"您是一个追求舒适的初级跑者，体重适中。",//跑者的描述
			person_word:[
				'舒适锻炼',
				'跑量小',
				'体重适中',
				'足弓正常',
				2
			],//跑者描述词	
		},
		//适合的跑鞋
		equips:{
			match:[
				{
					id : 1075,//装备id
					brand: 'nike', //品牌
					durable:3,//耐用度
					support:2,//支撑性
					buffer:3,//缓冲性
					eq_name:"美津浓Wave",//装备名
					image:"http://7niu.clouddn.com/a.png",//装备图
					sale_price:'694',//价格
				}
			],//完全匹配的跑鞋
			similar:[]//模糊匹配的跑鞋
		},
		//智能选装选项
		chooseItem:{
			feeling_type:'',//目的
			sex:'',//性别
			weight:'',//体重
			amount:'',//路程
			arch:'',//足弓
			spin:'',//内旋
			track_type:'',//路面
			price:''//价格
		}
	},
	//装备库
	equipment:{
		equipFilter:{
			status:'start/success/error',
			page_num:1,//第几页
			page_size:5,//多少个
			selectCate:'',//选中的装备分类
			selectEquipCate:'',//选中具体的装备类型
			list:[
				{}
			],//列表
		},
		equipDetail:{
			status:'start/success/error',
			data:{
				id:508,//装备id
				baseInfo:{
					images:[],//滚动图
					eq_name:'',//装备名
					inventory:'',//
					link:'',//购买链接
					is_hot:'',//是否热门
					sale_price:'',//销售价格
					brand:'',//品牌
					r_gender:'',//性别
					sport_type:'',//运动类型那个
					equipe_type:'',//装备类型
				},//基础数据
				otherInfo:{
					'equipe_tag':'',//标签
				},//
				suit_crowds:{
					arch_type:'',//足弓类型
					distance:'',//适合路程
					pronation_type:'',//
					fit_weight:'',//适合体重
					r_gender:'',//性别
					level:'',//等级
					summary:'',//一句话
				},//适合人群
				performance_param:{
					buffer:'',//缓震型
					support:'',//支撑性
					durable:'',//
					portablility:'',//
					const_perf:''//
				},//装备属性
				officialParams:{
					brand:'',//品牌
					series:'',//系列
					market_time:'',//上市时间
					fit_area:'',//适合路面
					fit_type:'',//适合类型那个
					r_weight:'',//重量
					level:'',//等级
					midsole_tech:'',//中底科技
					vamp:'',//材料
					detail_img:[],//详情图片
					outsole:'',//外底
				},//官方参数
			}
		}
	},
	//工具
	utils:{
		eplanation:{
			sex:'man/woman',//性别
			brand:'',//品牌
			onSelect:'MM',//选中的鞋码
			keyIn:'',//输入的数字
			sizes:{
				UK:'',
				MM:'',
				CM:'',
				UN:''
			}//码值
		}
	},
	//关于
	about:{
		//反馈
		feedback:{
			state:'start/success/error',//请求状态 
			feeling:'',//体验感觉
			suggest:'',//建议
		},
	},
	//搜索
	search:{
		searchKey:'',//搜索词
		history:[],//历史搜索记录
		sysRecommend:{
			status:'start/success/error',
			list:[
				{}//装备
			]
		},
		searchResult:{
			status:'start/success/error',//状态
			page_num:1,//页数
			page_size:6,//数量
			list:[
				{}//装备
			]
		}

	}
}